# Site settings
title: Neko_Yurico的小站 # 你的博客名字，可以定义修订
header-img: "img/green.jpg"
tagline: "cn"  
description: "nya~"  # 一句话描述你的博客
baseurl: ""
url: "http://nekoyurico.me/"  # 此处填写你的博客地址 
language: zh-CN     #主题语言
timezone: Asia/Shanghai    #中国的时区

# About/contact
owner: 
  name: "Neko_Yurico" # 填写作者信息：名字
  email: lyt12687459@gmail.com # 填写作者信息：邮箱
  bio: "nya~" # 填写作者信息：博客描述

# Data
gavatar: img/favicon.png # 浏览器地址栏小图标，可自定义更改
favicon: img/favicon.png # 浏览器地址栏小图标，可自定义更改

douban_username: 
twitter_username: 
facebook_username: 
weibo_username: 
zhihu_username: 
github_username: Neko-Yurico
bilibili_userid: 6968856
qq_userid: 945998493
mail_address: 945998493@qq.com
steam_userid: Neko_Yurico

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Neko_Yurico" # 你的名字
      header-img: "img/green.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :

# Disqus settings（https://disqus.com/）
disqus_username: NekoYurico # 你的discus username

# Analytics and webmaster tools stuff goes here
google_analytics:  # 填写你  google_analytics id
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
